---
apiVersion: v1
kind: Pod
metadata:
  name: back-end
  namespace: temp
spec:
  selector:
    matchLabels:
      app: service_demo_pod
  template:
    metadata:
      labels:
        app: service_demo_pod
    spec:
      containers:
      - name: simple-http
        image: python:2.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "echo \"<p>Hi from $(hostname)</p>\" > index.html; python -m SimpleHTTPServer 8080"]
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: service
  namespace: temp
spec:
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32322
    targetPort: http
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: front-end
  namespace: temp
spec:
  restartPolicy: Never
  containers:
  - name: demo-client2
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "echo 'GET / HTTP/1.1\r\n\r\n' | nc service-demo 80"]
